sonar.projectKey=prospectio-landing
sonar.projectName=Prospectio Landing
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts,**/main.tsx
sonar.typescript.tsconfigPath=tsconfig.json
